.travis.yml, project/plugins.sbt
This makes the build pass in Travis and fixes myriad version conflict issues. Coveralls still can't find this repo, though (but maybe it just needs some time).
* Encryption
* Audit trails
* LR reviews
=> Flailing attempts to get coveralls working

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
* Encryption
* Audit trails
* LR reviews
=> remove actor implicits where not needed

.travis.yml, project/Dependencies.scala, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/cluster-googleId-unique-key.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/cluster-unique-key.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/cluster.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/label.xml, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/LiquibaseConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/AllComponents.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/LeoComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/resources/reference.conf, src/test/resources/references.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/TestExecutionContext.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbSingleton.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/TestComponent.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
* Encryption
* Audit trails
* LR reviews
=> GAWB-2380, 2383, 2385: Store created clusters in a DB

project/Dependencies.scala
ran leo locally to make sure it didn't mess with anything
* Encryption
* Audit trails
* LR reviews
=> GAWB-2472: changing jackson version

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbSingleton.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
... and stop leaking `ActorSystem`s in tests. No JIRA.
* Encryption
* Audit trails
* LR reviews
=> Need to specify the MySQL driver for HikariCP to work

.travis.yml, docker/build.sh, docker/install.sh, docker/run-mysql.sh, docker/sql_validate.sh, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala, src/test/resources/reference.conf
* Encryption
* Audit trails
* LR reviews
=> Fixing Leo Build 

.travis.yml, docker/run-mysql.sh, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/TestComponent.scala
This makes it slightly harder to get access to the table components by doing `dbRef.some_db_query`, which is almost certainly not what you want. (You want to call `dbRef.inTransaction` and get a `DataAccess` from there instead.)
* Encryption
* Audit trails
* LR reviews
=> reshuffled database things into DataAccess class

docker/build.sh, docker/install.sh, docker/sql_validate.sh
No JIRA
* Encryption
* Audit trails
* LR reviews
=> Some build script updates

docker/run-mysql.sh
* Encryption
* Audit trails
* LR reviews
=> Jr fix test mysql

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeoException.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/TestComponent.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
* Encryption
* Audit trails
* LR reviews
=> GET cluster details endpoint that users can poll to see if they're ready yet

docker/run-mysql.sh
* Encryption
* Audit trails
* LR reviews
=> change mysql port #

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
Should make /ping pingable in swagger dev with no oauth, and give you an oauth button for the others
=> make swagger know about auth

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/SwaggerRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/SwaggerConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala
friends with https://github.com/broadinstitute/firecloud-develop/pull/621
=> Fix swagger auth

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/cluster-createdDate-default.xml, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
* Encryption
* Audit trails
* LR reviews
=> Gawb 2271 - Delete cluster endpoint for leonardo

README.md, hooks/README.md, hooks/apply-git-secrets.sh, hooks/commit-msg, hooks/pre-commit, hooks/prepare-commit-msg
=> Us gawb 2354

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
=> [GAWB-2002] Implement the GET /clusters endpoint to list notebook server clusters

jupyter-docker/Dockerfile, jupyter-docker/spark-defaults.conf.template
Tested. It lives!
In all cases:
=> GAWB-2613 Upgrade Hail version

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/DataprocConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
GAWB-2611 Add leo-demo app credentials
In all cases:
=> GAWB-2611 Add leo-demo app credentials

project/Dependencies.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCache.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dns/JupyterNameService.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/VCMockitoMatchers.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/MockProxyService.scala
Don't use Strings!  Use more specific value classes.
In all cases:
=> GAWB-2630 String Value Classes

README.md, docker/build.sh, jupyter-docker/build.sh
=> GAWB-2624: adding build/push for leo notebooks docker image

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/test/resources/reference.conf
=> fix for conf fail

project/Dependencies.scala
no Jira ticket.
security scans showed warnings on two third-party libraries. I've upgraded both of those.
I have not run unit tests locally - I can't get those running on develop branch, much less this one. I do see the tests pass in Travis for this PR, though.
In all cases:
=> update third-party dependency versions based on security scans

automation/docker/application.conf.ctmpl, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala
Part of GAWB-2617
In all cases:
=> Swintegration update to work with QA and recent changes

jenkins/run-integration-tests.sh
Run by Jenkins task `leonardo-PR-fiab-test`
In all cases:
=> Run integration tests in Jenkins: supports GAWB-2617

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
=> minor fix for bucket acls

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/VCMockitoMatchers.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
I haven't tested this on a FiaB (or anywhere else) yet. Caveat emptor!
In all cases:
=> GAWB-2653 Set init bucket acl to user specified SA and leo only

automation/Dockerfile-tests, automation/docker/hub-compose-fiab.yml, automation/docker/hub-compose.yml, automation/docker/run-tests.sh, automation/test.sh, jenkins/run-integration-tests.sh
No JIRA, but necessary for Jenkins.  Copied from UI and lightly edited.
In all cases:
=> Run integration tests in docker

project/Dependencies.scala, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/StatusRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/StatusService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/StatusRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockSamDAO.scala
=> [GAWB-2696] Leo: make /status endpoint

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/StatusService.scala
Pretty minor. Tested locally.
In all cases:
=> Fix swagger indentation and improve StatusService logging

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala
To match other cookie-auth'd endpoints in the Workbench ecosystem.
In all cases:
=> FCToken -> FCtoken

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
This code is executed by the Leo status checker. I noticed this when I deployed to alpha, which has no clusters.
In all cases:
=> Fix NPEs in health checker

src/main/resources/jupyter/init-actions.sh
Reviewing with `?w=1` would be helpful here.
In all cases:
=> Put pet creds on master and workers

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
=> GAWB-2887 Set hadoop auth properties and Dataproc staging bucket ACLs

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
=> Change staging bucket ACLs on staging bucket, not workspace bucket

project/Dependencies.scala
No Jira. Upgrades Jackson due to proactive security alerts from SourceClear.
In all cases:
=> upgrade jackson version

jupyter-docker/spark-defaults.conf.template
=> more than two executor instances, please

automation/docker/hub-compose-fiab.yml, automation/docker/hub-compose.yml, automation/docker/run-tests.sh, automation/src/test/scala/org/broadinstitute/dsde/workbench/ResourceFile.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala
Follow-on to #66 - you may want to look at that as well.
In all cases:
=> Attempt to de-flake GAWB-2617 tests

project/Dependencies.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/StandardUserInfoDirectives.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/UserInfoDirectives.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/HttpSamDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/SamDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/UserInfo.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/VCMockitoMatchers.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/HttpSamDAOSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockSamDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
Adopts https://github.com/broadinstitute/workbench-libs/pull/45.
No functional changes; just renaming classes. Tests pass.
In all cases:
=> Big libs update

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/DataprocConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/VCMockitoMatchers.scala
=> GoogleServiceAccount -> WorkbenchEmail

README.md
=> Added readme blurb

automation/project/Settings.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
Changes to allow deletion of error clusters(ClustErrs)
In all cases:
=> GAWB 2778 - Delete error clusters

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCache.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/TestClusterSupervisorActor.scala
=> GAWB-2797: Make ready clusters immediately proxy-able

CONTRIBUTING.md, LICENSE.txt, README.md
* Add project status to README
* Add Verily to LICENSE
* Add placeholder for external contribution guidelines until we roll out our full new CLA process.
In all cases:
=> Minor updates to repo documentation

src/main/resources/swagger/api-docs.yaml
=> fix for minor lies

src/main/resources/swagger/api-docs.yaml
=> Multiline keys must be indented

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
Seemed useful, and I added it to the indepth doc, so here it is.
In all cases:
=> added cluster creator to default set of labels

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/WebBrowserSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/util/WebBrowserUtil.scala
Copy of https://github.com/broadinstitute/firecloud-ui/pull/1089
In all cases:
=> Selenium upgrade to fix download issues

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, jupyter-docker/Dockerfile, jupyter-docker/jupyter_localize_extension.py, jupyter-docker/jupyter_notebook_config.py, jupyter-docker/run-jupyter-local.sh, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
No fc-dev change necessary.
In all cases:
=> GAWB-2386 stub /localize endpoint in Jupyter API

docker/run-mysql.sh
=> #103 remove dependency on dsde-toolbox

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, jupyter-docker/Dockerfile
Added another pip install to the Dockerfile.
In all cases:
=> GAWB 2608 - add AoU client library

docker/install.sh, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProvider.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProviderSpec.scala
=> Hussein's fix

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
=> scopes should be on the cluster SA, not the leo SA

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
Swat test to follow.
In all cases:
=> GAWB 3026 - give clusterserviceaccount access to dataproc bucket

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/firecloud/api/Orchestration.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala, project/Dependencies.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
=> GAWB-2838: BigQuery inside notebooks

automation/src/test/scala/org/broadinstitute/dsde/firecloud/api/Orchestration.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/api/WorkbenchClient.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala
Leo portion.  Sam/Rawls swat test changes also needed.
In all cases:
=> GAWB-3023 Test cluster pet credentials in a new project

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeoAuthProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockLeoAuthProvider.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
@ansingh7115 I still need to write some unit tests here. I think you have most of this -- your call whether to merge it into your branch. It's not going into develop
In all cases:
=> [nomerge] Better LeoService interop w/ auth providers

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoSpec.scala, project/Dependencies.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockSwaggerSamClient.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamClient.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SwaggerSamClient.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/WhitelistAuthProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/ProxyConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeoAuthProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockLeoAuthProvider.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockSwaggerSamClient.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
=> GAWB-2896: Do Sam Auth

README.md
=> testing zenhub behaviour on closed PRs

automation/docker/hub-compose-fiab.yml, automation/docker/hub-compose.yml, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/TestClusterSupervisorActor.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
=> GAWB-3108 Don't Delete Sam Cluster Resources

docker/build.sh
=> add docker tag for tests repo

automation/docker/application.conf.ctmpl, automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
Some useful Leo automation test updates I'm using in a forthcoming PR.  Sharing now by request so other users can use them too.
In all cases:
=> withNewGoogleBucket and withNewCluster / createNewCluster updates

automation/project/Dependencies.scala
=> ah - update test dependency

docker/build.sh
This should make the docker build exit properly if it fails.
In all cases:
=> add missing log to leo docker build

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/PetServiceAccountProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamServiceAccountProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
For testing #127 but may be more generally useful
In all cases:
=> Resurrect and update PetServiceAccountProvider

automation/project/Settings.scala
=> set up junit test reports

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/PetNotebookServiceAccountProvider.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/BucketHelper.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
Required by PetNotebookServiceAccountProvider, which is in turn required by #127 
In all cases:
=> Change getPetOrDefault() to return all available SAs

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/PetNotebookServiceAccountProvider.scala
Does not complete #127 - also need to test alternate auth providers.
Depends on https://github.com/broadinstitute/workbench-libs/pull/77
In all cases:
=> Preemptible test for #127

jupyter-docker/Dockerfile
upgrade the version of debian leo uses from jessie to stretch.
this is needed to support the R kernel
In all cases:
=> Ah debian upgrade

docker/build.sh
=> skip tests: set leonardo-tests latest image to env

automation/render-local-env.sh
=> Specify which repo we're checking out master in

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala
The google error message seems to have changed - no more "against it" in the message. 
This fixes the test.
In all cases:
=> [205]Intermittent test failure: failed to delete error'd cluster

automation/project/Dependencies.scala
To match version bumps in other repos
In all cases:
=> Update to latest service test: has gpalloc and thurloe fixes

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala
=> Ignore test.  See issues #204 and #228

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
=> Use GPAlloc

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
It looks like if `beforeAll` throws an exception, `afterAll` does not run. Therefore it's possible for Leo to allocate and not release a billing project.
I noticed this in e.g. [here](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/555/console), in which project `gpalloc-qa-master-3gxxp9u` is allocated, the cluster creation fails, and the project is not released.
In all cases:
=> Stop leaking billing projects in Leo tests

src/main/resources/jupyter/init-actions.sh
I extended https://github.com/DataBiosphere/leonardo/pull/239 a bit in this branch. I think this will help with cluster error debugging.
In all cases:
=> Init script timestamps

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
=> Exception type changed

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala, jupyter-docker/Dockerfile
https://github.com/DataBiosphere/leonardo/issues/254
https://github.com/DataBiosphere/leonardo/issues/257
Kudos to @ahaessly who actually did the work; I just tested.
In all cases:
=> Users unable to install R packages

automation/project/Dependencies.scala
=> upgrade service test libs

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
update to workbench libs so that we have to lookup the email address of a pet, can't just derive it.
In all cases:
=> Pet name change

docker/build.sh
=> skip tests: tag test image with git hash when building real env

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala
=> Add test for jupyter extensions

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala
=> Increase R package install test timeout

jupyter-docker/jupyter_delocalize.py
=> Improve delocalize docs

src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
Hopefully address intermittent unit test failures in Jenkins:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build/1882/console
In all cases:
=> Increase LeoRoutesSpec timeout

docker/run-mysql.sh
=> More verbose errors in run-mysql.sh

docker/build.sh, docker/run-mysql.sh
use a common name for the leo db for unit tests and running locally
In all cases:
=> change leo db name

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala
- Opening for feedback. Still need to rebase with `develop`.
- Addresses #282
=> Automatically set cookie for all /api endpoints

jupyter-docker/Dockerfile
This fixes the Leo docker build.
In all cases:
=> Upgrade Java version and add --ignore-installed

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala, jupyter-docker/Dockerfile, jupyter-docker/jupyter_localize_extension.py, src/main/resources/swagger/api-docs.yaml
Same as https://github.com/DataBiosphere/leonardo/pull/312, made a new PR to change to base.
In all cases:
=> Allow data URIs in jupyter_localize_extension. (#307)

ui/src/components/StatusIcon.js
Status icon for better "quick glance" cluster status recognition. See it in gif form [here](https://docs.google.com/document/d/1_EDQR347f7CsTxy5OWiXOn3iV9IKwOv-M9wPmilWUlU)
In all cases:
=> User interface: dynamic status icon.

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20180515_cluster_dateaccessed.xml, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterErrorComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ExtensionComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/InstanceComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
Added a new dateAccessed column to the Cluster table.
In all cases:
=> Issue 367: Auto Freeze - Phase 1

leonardo-example.conf, src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/ServiceAccountProviderHelper.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/AutoFreezeConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterAccessDateActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterDateAccessedActor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterDateAccessedSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/MockProxyService.scala
1. Created akka actor to update the DateAccessed.
2. Added configs for auto freeze
In all cases:
=> Issue 368 - Auto freeze phase 2

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala, jupyter-docker/Dockerfile
https://github.com/DataBiosphere/leonardo/issues/398
Confirmed this manually and via test.
In all cases:
=> [Issue 398] Install libxml2-dev which is a system requirement for some R packages

project/Dependencies.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala
=> Add Google Cloud Source Repositories scopes to the pet SA on the cluster

project/Dependencies.scala
=> Fix sbt eviction warnings

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
=> MLR takes a while to install

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
This PR depends on https://github.com/broadinstitute/firecloud-automated-testing/pull/42 
In all cases:
=> Fix Leo automation subproject eviction warnings

automation/project/Dependencies.scala, automation/project/Settings.scala
=> Update Scala version to 2.12 in auto-tests

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/config/LeoAuthToken.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoConfig.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
=> Enable independent config values

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
=> Leo retries 403 error until it times out (500) if Dataproc is disabled

docker/build.sh, leonardo-example.conf, project/Dependencies.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/IamProxyAuthProvider.scala
This new provider uses client credentials to test permissions
on a project before granting access to a user. Thus, it proxies
the user's IAM permissions.
In all cases:
=> Add IamProxyAuthProvider.

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20180625_autopause_threshold.xml, src/main/resources/reference.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterErrorComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ExtensionComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/InstanceComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterDateAccessedSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterSupervisorSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
=> Allow users to configure autopause settings for cluster

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SamAuthProvider.scala
=> Retry op when getting 401 status from Sam

jupyter-docker/jupyter_notebook_config.py, jupyter-docker/run-jupyter-local.sh
This has been manually tested.
In all cases:
=> Update jupyter notebook terminal to use bash instead of dash

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala
=> Updated dataprocdisabled to look at reason instead of message

automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/config/LeoAuthToken.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookHailSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInstallSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/PingSpec.scala
=> Flaky test Jupyter kernel fix

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPyKernelSpec.scala, jupyter-docker/Dockerfile
=> Replaced gcloud with relevant subpackages and pegged their versions

automation/project/Dependencies.scala, automation/src/test/resources/logback-test.xml, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookHailSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInstallSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookLocalizeFileSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPyKernelSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookRKernelSpec.scala
=> Tagging some Leo tests as SmokeTest

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookHailSpec.scala
=> increase hail tutorial timeout

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
There were some compilation errors that arose from my last PR (https://github.com/DataBiosphere/leonardo/commit/f69247377be78566860942d15d11558543e634e9), probably from a merge conflict. This PR fixes those issues.
In all cases:
=> Fixed compilation errors from merge conflict

automation/build.sbt, automation/project/build.properties
=> Decrease number of test JVM

automation/build.sbt, automation/project/Dependencies.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterFixtureSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPyKernelSpec.scala
BigQuery queries sometimes take longer than 1 minute. Recommend increasing BigQuery timeout in test from 1 min to 5 min
In all cases:
=> Minor Leo test improvements

automation/project/Dependencies.scala
=> update library dependency version

jupyter-docker/scripts/extension/jupyter_install_notebook_extension.sh, src/main/resources/jupyter/init-actions.sh, src/main/resources/swagger/api-docs.yaml
=> Allow http/js nbextension

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterExceptionSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInstallSpec.scala
=> Set default cluster monitorDelete = false

src/main/resources/jupyter/init-actions.sh
See https://github.com/DataBiosphere/leonardo/issues/570
Hoping this helps test flakiness due to timeouts pulling the notebooks image from GCR.
In all cases:
=> Retry docker-compose

src/main/resources/jupyter/init-actions.sh
See https://github.com/DataBiosphere/leonardo/issues/597
I have not run automated tests yet, opening this PR to get test results.
In all cases:
=> Add a generic bash retry function which actually works

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala
=> Rework test "deleting an already deleting cluster should be a no-op"

src/main/resources/jupyter/init-actions.sh
=> Add retries to apt-get update

ui/package-lock.json, ui/package.json
WARNING: I don't know what I'm doing!
This is to hopefully address the yellow warning on the Leo github page: https://github.com/DataBiosphere/leonardo
What I did:
1. ```npm audit fix --force```
2. committed the changes
The UI still loads on `npm start` so hopefully it is OK. (We don't actually run this UI in production, it was contributed externally.)
In all cases:
=> Fix node security vulnerabilities

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterExceptionSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/google/GoogleModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala
=> Creating clusters cannot be deleted

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookRKernelSpec.scala
=> ignore non-deterministic test

src/main/resources/reference.conf
They want to start loading notebooks in an iframe a la Saturn.
In all cases:
=> Add AoU domains to CSP

.github/PULL_REQUEST_TEMPLATE.md
=> Updating PR Template 

src/main/resources/reference.conf
Added:
- https://stable.fake-research-aou.org
- https://app.terra.bio
In all cases:
=> Added AoU and Terra domains to CSP

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala
=> Retries for "Jupyter kernel is not ready" error

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPySparkKernelSpec.scala
=> Temp: ignore PySpark3 test until Docker upgrades are merged

src/main/resources/jupyter/init-actions.sh
There was a automation test failure due to the following error in init-actions 
```
+ docker exec jupyter-server mkdir -p /home/jupyter-user/.jupyter/custom
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 12124 to cgroups caused \"failed to write 12124 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/2e34c66c36034471a17f0455a917f9bcff14e3a2b090daac139c17e278772c76/cgroup.procs: invalid argument\"": unknown
```
This PR is a hopeful attempt that retries will fix this issue.
In all cases:
=> add retries to docker execs in init-actions

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPySparkKernelSpec.scala
=> Log time it takes to do the Hail import and bump timeout to 10 min

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala, automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala, jupyter-docker/Dockerfile, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml, src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20181114_scopes.xml, src/main/resources/reference.conf, src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/DataprocConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/GoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/AllComponents.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ScopeComponent.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterEnrichments.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/MockGoogleDataprocDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModelSpec.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
=> Make cluster scopes definable by app/user

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookCustomizationSpec.scala
=> browser timeout due to long inactivity

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala
=> Just compare clusters by id

docker/jupyter/Dockerfile, docker/jupyter/scripts/run-jupyter.sh, src/main/resources/jupyter/init-actions.sh
=> Build python3.6 from source

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
=> Issue 733: If google marks cluster as Error but doesn't return error code then don't continue to monitor the cluster

docker/jupyter/Dockerfile, src/main/resources/jupyter/init-actions.sh
=> Issue 751 : Install gcsfuse on clusters by default

docker/jupyter/Dockerfile, docker/jupyter/scripts/hail/spark_install_hail.sh
Not ready yet - opening PR to check how the tests do.
In all cases:
=> Upgrade hail to the latest 0.2 build

example-notebooks/RonaldoExample.ipynb
Added sample code to run googleCloudStorageR
In all cases:
=> Update Ronaldo example notebook

automation/test.sh, docker/install.sh
=> sbt batch mode so it doesn't hang while building

docker/build.sh, docker/jupyter/Dockerfile
`ha.pool.sks-keyservers.net` seems to be flakey..
In all cases:
=> Try using keyserver.ubuntu.com

src/main/resources/jupyter/init-actions.sh
=> Adding retries to hopefully fix automation test failures

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/HttpJupyterDAO.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/HttpJupyterDAOSpec.scala
=> umm, why didn't I add the test before

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala
=> add more logging

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala
I think this fixes https://github.com/DataBiosphere/terra-ui/issues/1550. Starting with PR [871](https://github.com/DataBiosphere/leonardo/pull/871), we started allowing user-specified Spark properties which were unfortunately overwriting the properties we set internally, including `dataproc:dataproc.allow.zero.workers`. This PR should make it so we merge _all_ the properties.
This still needs verification on a fiab.
In all cases:
=> Don't overwrite Dataproc properties

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookPyKernelSpec.scala, docker/jupyter/Dockerfile
See https://github.com/DataBiosphere/leonardo/issues/891
Waiting on automation tests.
In all cases:
=> gcc is broken in the Jupyter image

src/main/resources/swagger/api-docs.yaml, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeoException.scala, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
=> lint cluster name before create cluster with dataproc

src/main/resources/jupyter/init-actions.sh, src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/ZombieClusterConfig.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ZombieClusterMonitor.scala, src/test/resources/reference.conf, src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ZombieClusterMonitorSpec.scala
=> Jc creation zombie

src/main/resources/swagger/api-docs.yaml
=> fix indentation

src/main/resources/jupyter/safe-mode.js
Includes #944 for IA-958.
In all cases:
=> [IA-959][risk=no]Hide more functionality in Safe Mode extension

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala, src/main/scala/org/broadinstitute/dsde/workbench/leonardo/util/BucketHelper.scala
=> create init bucket in user's project

docker/jupyter/custom/jupyter_delocalize.py, docker/jupyter/custom/test/jupyter_delocalize_test.py, docker/jupyter/custom/test/test-requirements.txt, src/main/resources/jupyter/jupyter_notebook_config.py
Still needs tests.
In all cases:
=> Implement initial Welder server extension

docker/jupyter/custom/jupyter_delocalize.py, docker/jupyter/custom/test/jupyter_delocalize_test.py
=> Welder ext: handle deletes and errors

project/Dependencies.scala
Consumes the change from https://github.com/broadinstitute/workbench-libs/pull/251. Will change to non-SNAP once the wb-libs PR is merged.
In all cases:
=> Update wb-libs google hash for nullcheck fix
