DataBiosphere/leonardo

Dockerfile
README.md
docker/build.sh
docker/install.sh

* Encryption
* Audit trails
* LR reviews

Adding simple Dockerfile

---

.gitignore
src/main/resources/logback.xml
src/main/resources/reference.conf
src/main/resources/swagger/README.md
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/SwaggerRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/SwaggerConfig.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala

Also reference.conf and logback
* Encryption
* Audit trails
* LR reviews

GAWB-2339 Add swagger

---

Dockerfile
docker/build.sh
project/Settings.scala
project/Version.scala

GIT_MODEL_HASH is a holdover from rawls publishing rawlsModel and is confused.

GIT_MODEL_HASH is the wrong word

---

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/cluster-extensionUri-column.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/cluster-jupyterExtensionUri-column.xml
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/DataprocConfig.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/resources/reference.conf
src/test/resources/test-init-actions.sh
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

https://broadinstitute.atlassian.net/browse/GAWB-2535
Depends heavily on: https://github.com/broadinstitute/firecloud-develop/pull/659
Basic flow:
1. Cluster PUT request accepts an optional gs:// path to a tar.gz containing extension files
- For testing I've been using: `gs://rtitle-jupyter-extension/my_extension.tar.gz`
2. The gs:// path gets saved in the CLUSTER table in a new column
3. The gs:// path is templated into the init-actions.sh script
4. init-actions.sh copies the tarball to the local VM using `gsutil cp`
5. `cluster-docker-compose.yml` mounts the tarball inside the jupyter docker container
6. init-actions.sh calls `install-jupyter-extension.sh` on the jupyter-server docker via `docker exec`
- I didn't see a good way of doing this in the docker-compose, i.e. running an …

[GAWB-2535] Notebook Service: support user-defined notebook extensions

---

src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala

It doesn't look great in the Swagger UI rendering but it's there now. On request of the AoU folks.
In all cases:

Add cluster status enums to Swagger

---

jupyter-docker/build.sh

Still need to confirm this, but I think what was happening was that `jupyter-docker/build.sh` was using the Leo Dockerfile in the base directory instead of the `jupyter-docker/Dockerfile`.
In all cases:

Potential fix for jupyter docker build

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala

I noticed a lot of INFO spam while ssh'ed in to Leo. I don't think we should log the params on every request to `GET /api/cluster`.
In all cases:

Don't need to info log on every request

---

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20170811_cluster-unique-key.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20171010_cluster_unique_index.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20171011_cluster_destroyedDate_not_null.xml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

Updated the unique constraint to include destroyed date. Added default destroyed date on cluster create. Only one cluster is active at a time. 
In all cases:

GAWB - 2627 - Allow multiple clusters with same name

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/StandardUserInfoDirectives.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/UserInfoDirectives.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/UserInfo.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/MockUserInfoDirectives.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala

Added `UserInfo` case class and `UserInfoDirectives` which extracts UserInfo's out of Leo http requests. This is not actually used yet, but will be needed in the future for whitelist auth and pet service accounts.
I code-borrowed pretty heavily from Sam. It works locally.
In all cases:

Add basic UserInfo checking to Leo. This is not actually used yet.

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/ClusterResourcesConfig.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/resources/reference.conf
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

It turns out you can call `.setServiceAccountScopes()` at cluster creation time, and setting OAuth2Scopes lets the service account talk to FC without the local key json. (i.e. it has the right scopes on the metadata server.) Thanks to Josh Mandel for discovering this. This essentially resolves https://broadinstitute.atlassian.net/browse/GAWB-2649 and removes the need for https://broadinstitute.atlassian.net/browse/GAWB-2615.
I basically updated `GoogleDataprocDAO` to do this, and removed the existing code related to pushing the SA key to the init bucket & cluster. I verified locally creating a cluster and running the demo script.
PR friend: https://github.com/broadinstitute/firecloud-develop/pull/721
I, the …

Set OAuth2 scopes on cluster creation, and don't send the sa key json to the cluster

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/DataprocDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/GoogleDataprocDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/MockGoogleDataprocDAO.scala

I found this issue while testing pet service accounts. The Google auth tokenInfo.expiresIn was being treated as milliseconds rather than seconds, causing tokens to prematurely expire.
In all cases:

Fix bug with cookie auth expiration

---

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20171218_cluster_indexes_serviceAccount_and_status.xml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala

Fixes a concurrency bug, helpfully exposed by Leo-swat.
Currently we add the Dataproc Worker IAM role to the pet SA on cluster creation, and remove it when the cluster reaches a terminal state (either Running or Error). However if the user creates 2 clusters at the same time we can reach a situation where the role is removed when the _first_ cluster finishes, leaving cluster 2 in a bad state. (It also seems to leave the pet's IAM roles in a bad state in general, preventing future cluster creation -- not exactly sure why).
The fix is to remove the IAM role only if there are no other clusters for that user with CREATING status. That way the role is only removed after the _last_ cluster is created. I verified with unit tests and watching the IAM console during a swat run (passing swat link: …

Dataproc Worker concurrency bug

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/WhitelistAuthProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeoAuthProvider.scala
src/test/resources/reference.conf
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockLeoAuthProvider.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

This probably isn't exactly right (I haven't tested it, it doesn't compile, and it's waiting on a new Sam API that doesn't exist yet!), but it's in roughly the right ballpark, I think.
The idea is to use the Leo SA to call Sam, asking for the pet's keys for a particular user. From there we can build a credential and create a token from that credential. I cached the token because why not.
This means the AuthProvider needs to take an instance of a ServiceAccountProvider so I went ahead and did that too.
In all cases:

Getting pet SA token from Sam

---

src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/TestProxy.scala

I suspect the reason for this is we weren't actually waiting on `bindingFuture`, which completes when the TCP binding is ready and the server is ready to accept requests. So it was possible for the proxy tests to run before the backend server was actually up.
Will kick off a few Travis runs to test.. 
In all cases:

GAWB-3082: Fix intermittent unit test failure in ProxyRoutesSpec

---

src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala

Maybe this will do it. The `PatienceConfig` isn't affecting the route timeouts; there is a separate implicit field called `RouteTestTimeout`.
Up to 7 passing Jenkins builds, haven't yet seen a failure..
In all cases:

Fix ProxyRoutesSpec for real

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/LeoAuthProviderHelper.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/PetsPerProjectServiceAccountProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/ServiceAccountProviderHelper.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeoException.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/ServiceAccountProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/LeoAuthProviderHelperSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockPetServiceAccountProvider.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/MockPetsPerProjectServiceAccountProvider.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/SamAuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/ServiceAccountProviderHelperSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

I made a `LeoAuthProviderHelper` and `ServiceAccountProviderHelper` which wrap `LeoAuthProvider` and `ServiceAccountProvider` respectively and recover all thrown exceptions to `LeoException`. I was thinking this would be a better approach than assuming the providers are doing exception handling themselves (because they may not be written by us).
Also added some specs to make sure exception handling is working. I don't think additional auto tests are needed for this. I haven't run auto tests yet. :)
In all cases:

Leo/Sam auth: handle Sam API exceptions in SamAuthProvider

---

docker/build.sh
docker/run-mysql.sh
jupyter-docker/build.sh

Make it easier for users of Google Container Registry to build
images. Also make the command line parsing a little less sensitive
to order and less dependent on environmental vars for config.

docker/build.sh; update flags, allow GCR images.

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20180205_cluster-error.xml
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/AllComponents.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterErrorComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterErrorComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/LabelComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala

Added a new table to store the error details for errored clusters. 
In all cases:

Issue - 141- Save error details for errored clusters

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala

I can't make #204 fail.  Shuld we turn it back on?
In all cases:

Re-enable flaky test because it seems to be fine?

---

jupyter-docker/Dockerfile

Tornado 5.0 was just released which breaks with our python3 version: http://www.tornadoweb.org/en/stable/releases/v5.0.0.html#mar-5-2018
This pegs it at the previous version, 4.5.3.
Note we need to peg ALL our dependencies (see https://github.com/DataBiosphere/leonardo/issues/148). This PR is just a quick fix.
In all cases:

Peg tornado at version 4.5.3

---

automation/project/Dependencies.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala

I think this was probably causing https://github.com/DataBiosphere/leonardo/issues/204. Our calls to `googleStorageDAO.copyObject` and `googleStorageDAO.setObjectAccessControl` were racy, which probably made the latter fail intermittently, which manifested as 403 errors in a notebook.
Note we've encountered some other errors related to this test (see https://github.com/DataBiosphere/leonardo/issues/228). I haven't been able to reproduce those locally, I'm going to run it a bunch of times in Jenkins.
In all cases:

Wait on futures in preemptibles test

---

src/main/resources/jupyter/init-actions.sh

`apt-get update` failures have caused intermittent cluster creation errors in automation tests.
Note: Google DataLab does the same thing in their init script: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/datalab/datalab.sh#L21-L29
In all cases:

Retry apt-get update in init script because it's flakey

---

docker/run-mysql.sh

Jenkins instances keep getting in a bad state because there are 2 mysql containers running. It may be due to this PR: https://github.com/DataBiosphere/leonardo/pull/233/
For now let's just try and clean up both names.
In all cases:

Clean up mysql containers

---

automation/project/Dependencies.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala

This should help make automation tests easier to debug.
In all cases:

Auto tests: log cluster errors and save init script logs as build artifacts

---

jupyter-docker/Dockerfile

The library we're installing is an old version. The AoU integration is going to install this via a user script, or just in a notebook via `!pip install`.
In all cases:

Remove AoU client library because it's outdated

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala

This PR broke this test in dev: https://github.com/DataBiosphere/leonardo/pull/250
Unfortunately tests still passed at PR time because of this: https://github.com/DataBiosphere/leonardo/issues/157. Oops :(
In all cases:

We do not install the AoU library by default anymore

---

project/Dependencies.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/BucketHelper.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

I think our cleanup-on-error was causing https://github.com/DataBiosphere/leonardo/issues/262, which has been observed several times by the AoU team. I made some effort to clean up our cleanup. See comments below.
Automation tests passed against this branch: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/3306/. I was looking into the possibility of recreating the "stuck in Creating" issue in an automation test. However it's a little tricky because a) it's hard to simulate errors in cluster PUT requests and b) the issue is due to a race condition between actors which is hard to reproduce reliably.
In all cases:

Improve cluster cleanup-on-error logic

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/CorsSupport.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/TestProxy.scala

Issue: https://github.com/DataBiosphere/leonardo/issues/272
Summary: Jupyter sets `Access-Control-Allow-Origin: *`, but the Leo proxy overrides it in some cases (when the origin is a different domain than Leo). Previously this was causing 2 `Access-Control-Allow-Origin` headers (with different values) which were causing browser exceptions in some cases.
Changed the proxy routes to do a replace instead of append, and added a unit test to reproduce the issue. 
In all cases:

Issue 272: CORS headers are double-set for proxied Jupyter rest API

---

jupyter-docker/Dockerfile

Offering this as one possible solution. I'm currently attempting to install git in my user script instead which would also be an acceptable solution, but without success (#265 to try and help me debug that one). The value here is that it would enable using the following form to pip install custom packages:
```
pip install --upgrade  --user "git+https://github.com/calbach/pyclient.git@ch/config-json#egg=aou_workbench_client&subdirectory=py"
```
This fails if you don't have git installed. For AoU, it would be convenient to use this technique for testing unreleased changes to the Python client library.
In all cases:

Include git in Leo docker image

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
project/Dependencies.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/TestProxy.scala

- Updates akka and akk-http versions
- Adds a step in httpResponse processing to replace Content-Disposition header's filename param with correct one 
FIAB this branch is currently running on if you want to check it out:  fiab-ansingh-ruling-racer (35.192.122.4)
In all cases:

LEO-214: Fix Downloaded Notebook Name

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala

I meant to unignore this test as part of https://github.com/DataBiosphere/leonardo/pull/238.
I think a merge conflict resolution probably put the ignore back (hard to tell `in` from `ignore`).
Will run a few builds off this branch to make sure it's really passing reliably.
In all cases:

Really unignore preemptibles test

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/resources/reference.conf
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

Put the init and staging bucket prefixes at the beginning of the bucket name. I'm doing this because the UUID often cuts off `-staging` from the bucket name, which makes it harder to distinguish between a cluster's init and staging buckets.
In all cases:

Put the init/staging bucket label at the beginning of the bucket name

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/PetClusterServiceAccountProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/PetNotebookServiceAccountProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SamAuthProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SamProvider.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SwaggerSamClient.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/MockSwaggerSamClient.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SamAuthProviderSpec.scala

See https://github.com/DataBiosphere/leonardo/issues/290
Added invalidate-cache-and-retry logic to Sam `notifyClusterCreated` and `notifyClusterDeleted`. I only updated those methods because only they use the pet; all other Sam calls are done with the user's token or the Leo service account.
I also started a bit conservative: I am only retrying 401s and 50xs from Sam, and only retrying twice.
I am going to run a bunch of UI tests against this PR to see if it helps the intermittent failures.
In all cases:

290: Add retries to SwaggerSamClient

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala

I think this behavior probably changed with the "kernel flicker" fix. It was probably not caught at PR time due to https://github.com/DataBiosphere/leonardo/issues/157
Anyway seeing if this change fixes it. 
In all cases:

Fix selenium kernel shutdown condition

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/ProxyService.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/util/BucketHelper.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/util/CookieHelper.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/util/RouteHelper.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

- Fixes a bug where cookie expiration time was erroneously converted into milliseconds while being cached in `ProxyService`.
- Factors out helper methods that are now being utilized by multiple `Routes`.

Fix for cookie age unit bug

---

automation/project/Dependencies.scala

Removes the Config setting for choosing "default" projects like broad-dsde-dev/broad-dsde-alpha.
In all cases:

GAWB-3353: Update service-tests to 0.8-cd592ce

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/util/BucketHelper.scala

Kaan's fix for https://github.com/DataBiosphere/leonardo/issues/317 will be the better fix, since it will do this in 1 Google call and will make explicit the dependency on project-owners/editors permissions instead of relying on defaults. But I was thinking we could merge this for now to unblock users. It basically reverts the staging bucket behavior prior to https://github.com/DataBiosphere/leonardo/pull/294.
In all cases:

Set staging bucket ACLs in a separate call

---

src/main/resources/jupyter/cluster-docker-compose.yaml
src/main/resources/jupyter/init-actions.sh

We are setting up a system where a user's root directory can sync with GCS. We can automate parts of the setup inside the Jupiter-docker if the user's email is visible in the docker environment. This change simply takes advantage of a substitution variable that was already present.

Add the creator's email to the jupyter environment

---

jupyter-docker/Dockerfile

This change updates the default jupyter docker file to use R 3.4 by using the debian installation instructions [here](https://cran.r-project.org/bin/linux/debian/).
Additionally, I have removed a routine that clears /var/lib/apt/lists/*. Because docker image layers are segmented by RUN commands, the clearing doesn't save any storage, it just marks the files as unavailable in the top-most layer. For this optimization to work, we would need clear out the cache after every use of `apt-get update && apt-get install ...`
In all cases:

jupyter-docker: update R to v3.4

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala
jupyter-docker/Dockerfile
src/main/resources/jupyter/init-actions.sh

https://github.com/DataBiosphere/leonardo/issues/322
A few users have reported this. In a notebook, `pip install tensorflow` throws a permission error because the install directory is owned by root. `pip install tensorflow --user` works, but it's easy to forget to do that. This configures pip to install as user by default. 
In all cases:

Pip install as user by default

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala

I'm hoping this fixes the test flakes:
```
Leonardo notebooks should be able to pip install packages using Python 2
Leonardo notebooks should be able to pip install packages using Python 3
```
The flakiness seems related to restarting the kernel using Selenium. Creating a brand new notebook should be more reliable, and still exercise this feature. 
In all cases:

Do the pip install verification in a new notebook

---

ui/src/components/ClusterCard.js
ui/src/components/DeleteDialog.js

This change adds a delete button to each cluster card. The button will create a confirmation dialog when clicked. Once confirmed, a delete request is sent. On success, the cluster's status is manually set to "Deleting".
See the new component in action [here](https://docs.google.com/document/d/1dcN4Edbuiny8e9CIEp4KrY5AZGIT9ULWAuHM78BrdkA)
In all cases:

User Interface: cluster delete button & dialog.

---

ui/src/components/CreateClusterForm.js
ui/src/components/CreateClusterModalButton.js
ui/src/components/ListStateContainer.js

Add a cluster-create button that launches a modal. The modal runs simple name validation and builds the request. Additionally, the modal will briefly show a progress spinner while waiting for the API to return a successful response. On success the modal notifies the application state container to refresh the entire list.
See a screenshot of the modal [here](https://docs.google.com/document/d/16sEFuGvr4omhDiB1iVxc1ogeYkb1zIUL-6txKew8oJ4)

User Interface: create cluster modal and form

---

jupyter-docker/jupyter_delocalize.py
jupyter-docker/test/jupyter_delocalize_test.py

This makes the UI a bit snappier on save, rename, delete.
In all cases:

mv gsutil delocalize to the background

---

automation/src/test/resources/diff-tests/hail-tutorial.ipynb
automation/src/test/resources/diff-tests/import-hail.ipynb
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebooksListPage.scala
jupyter-docker/Dockerfile
jupyter-docker/kernelspec.sh
jupyter-docker/pyspark_kernelspec.tmpl
jupyter-docker/python_kernelspec.tmpl
src/main/resources/jupyter/init-actions.sh

The `Python` kernels no longer comes with Spark installed, which cuts more than 10 seconds from the kernel start-up time.
The newly added `PySpark` kernels have the former `Python` kernels' functionality.
All four kernels are displayed on the notebook UI by default.
In all cases:

Separate Python and Spark kernels

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala

This was a mistake on my part. In https://github.com/DataBiosphere/leonardo/pull/349 I added the `stopAfterCreation` boolean parameter to `ClusterRequest` thinking it was optional, but I misunderstood how spray-json works and accidentally made it required. This means clients that don't set this parameter (e.g. FireCloud and AoU) currently can't create clusters in Leo-dev. This fixes it. I'd like to merge this quickly to fix dev.
In all cases:

Make stopAfterCreation truly optional in the create cluster request

---

jupyter-docker/user-scripts/uninstall_spark_kernels.sh

In response to @calbach's request on #346, we are adding a user script that can be specified at cluster creation time in order to hide the Spark kernels (PySpark 2 and 3) so it looks like
**Note:** As with other user scripts, the GCS object containing the script needs to be readable by the user's pet service account. More information on whether it's necessary to manually grant read permission to the bucket and if so, how to do it, can be found [here](https://software.broadinstitute.org/firecloud/blog?id=11342).

User script to hide spark kernels

---

jupyter-docker/Dockerfile

Looks like `ggplot` pulls the latest version of `statsmodels`, which recently changed from 0.8.0 to 0.9.0 and broke things. This pegs `statsmodels` to 0.8.0 to resolve the issue.
In all cases:

Peg the statsmodels dependency for compatibility

---

ui/.env
ui/public/index.html
ui/public/manifest.json
ui/src/components/ClusterCardList.js
ui/src/components/CreateClusterForm.js
ui/src/components/ListStateContainer.js

This PR includes a few UI fixes and config features.
* Bugfix: creator filter should have used '_labels' url field.
* Feature: pre-populate the project field via the config.
* Feature: lock the project field via the config.
* Other fix: make page title display `Leonardo` instead of `React App`.
In all cases:

User Interface: new options and other fixes

---

docker/build.sh
jenkins/jenkins_build.sh

Made the following changes to the Leo build script:
1. Added `--service-account-key-file` option to `build.sh` which if set, will cause the script to call `gcloud auth activate-service-account`. This is needed for pushing to our public [GCR repo](http://us.gcr.io/broad-dsp-gcr-public).
2. Added `jenkins_build.sh` with the DSP-specific logic: vault token/paths, service accounts, repos, etc. The idea is to make [leonardo-build](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build/) just call this script directly.
The scripts work locally & in [Jenkins](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build/2208/console). Plan for rollout:
1. Merge this PR; it should not have any effect initially. Make sure dev deploy+tests pass.
2. Update Jenkins leonardo-build …

Add support for obtaining a GCR service account from vault

---

src/main/resources/swagger/api-docs.yaml

When syncing to AoU, we noticed these validation errors. We're using this gradle plugin to perform the validation: https://github.com/int128/gradle-swagger-generator-plugin/blob/26c71f3ab4ea7002a7f786f550e3dab502f58466/src/main/groovy/org/hidetake/gradle/swagger/generator/ValidateSwagger.groovy
In all cases:

Fix Swagger validation errors

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInteractionSpec.scala
jupyter-docker/Dockerfile

I had previously set  `LC_ALL` to  `en_US.UTF-8` but it didn't actually work because that locale wasn't installed. :( Updated the Dockerfile to actually install the locale and updated the test to verify that the characters get displayed instead of just checking the EV.
Context: this is needed for Nurses Health, who is using mlr/skimr in notebooks and would like these funky histograms to display.
In all cases:

Fix locale so unicode characters actually display

---

jupyter-docker/jupyter_notebook_config.py
src/main/resources/jupyter/custom.js

Request from @zarsky-broad to allow loading the Jupyter notebook in an iframe.
See: https://jupyter-notebook.readthedocs.io/en/latest/public_server.html?highlight=server#embedding-the-notebook-in-another-website
Note: I haven't tested this myself yet. One thing I'm curious about is whether single-tab mode is undesirable when NOT running in an iframe (e.g. the AoU case). If so, we might want to make this configurable.
Also: this might screw up the tests
In all cases:

Experimental: allow opening Jupyter in an iframe

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookRKernelSpec.scala

Comparing with `include` instead `shouldBe` in `NotebookRKernelSpec` test `should be able to install mlr`.
actual cell output: 
`Loading required package: ParamHelpers
Warning message:
“replacing previous import ‘BBmisc::isFALSE’ by ‘backports::isFALSE’ when loading ‘ParamHelpers’”") `
expect cell output:
`Loading required package: ParamHelpers`
Stacktrace:
```
[info] - should be able to install mlr *** FAILED *** (2 minutes, 15 seconds)
[info]   Some("Loading required package: ParamHelpers
[info]   Warning message:
[info]   “replacing previous import ‘BBmisc::isFALSE’ by ‘backports::isFALSE’ when loading ‘ParamHelpers’”") was not equal to Some("Loading required package: ParamHelpers") (NotebookRKernelSpec.scala:98)
[info]   org.scalatest.exceptions.TestFailedException
``` …

Fix test "should be able to install mlr"

---

ui/src/components/CreateClusterForm.js

TLDR: see title. Because the config system passes empty values as an empty string, cluster creation fails using the new default startup script value derived from the config if that value is set to blank (or if a user overrides the value with a blank.
In all cases:

UI: fix bug; null jupyterUserScriptUri fails to create cluster.

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala

See https://github.com/DataBiosphere/leonardo/issues/459 and https://docs.google.com/document/d/1F_275KEwfs2hivu1yyhgd7WkZzNVqUjgCqSId0ruh-8/edit#.
Ignore flaky verification until the underlying issue can be investigated.
In all cases:

Ignore flaky preemptible test

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala

Description in https://github.com/DataBiosphere/leonardo/issues/481
In all cases:

Make cluster startup script backwards compatible

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SamAuthProvider.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SamAuthProviderSpec.scala

SamAuthProvider no longer checks tokenExpiresIn of userInfo when comparing cache keys

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala

I'm still seeing a lot of test failures due to 401s from GCS. See: https://github.com/DataBiosphere/leonardo/issues/460
I noticed that we are potentially validating a lot of GCS objects (user scripts, extensions), and fetching a new token from Sam for each validation. I changed it to just fetch 1 token at the beginning and reuse it to validate each object. Maybe that will help flakiness.
Note this PR doesn't yet add retries, but that might be the next step if this doesn't fix it.
In all cases:

Reuse pet token for all GCS validations instead of re-fetching token each time

---

jupyter-docker/Dockerfile

http might be faster anyway
In all cases:

Use http mirror because of broken cert

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterExceptionSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeoException.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookInstallSpec.scala
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/MockGoogleDataprocDAO.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

**The flow of `LeonardoService` methods called upon `PUT /api/cluster/v2/{googleProject}/{clusterName}`:**
1. `processClusterCreationRequest`: We wait for it to complete before completing the request.
2. `initiateClusterCreation`: Start cluster creation work if the cluster doesn't already exist. Any better naming suggestions are welcome.
3. `stageClusterCreation`
4. `completeClusterCreation`
5. `createGoogleCluster` & `AuthProvider.notifyClusterCreated`
**Other notes:**
- Errors encountered during the asynchronous portion (i.e. the part API request completions no longer wait for) are persisted in DB, which is now the only way to retrieve them (as opposed being part of the API response in v1)
I, the …

Async Cluster Creation - Season Finale!

---

src/main/resources/reference.conf

The CSP `connect-src` currently contains `wss://*.broadinstitute.org:*` which works for non-prod, but the prod domain is `notebooks.firecloud.org`. This adds `wss://notebooks.firecloud.org:*` to CSP.
The failure mode was the Jupyter UI loaded, but the kernel (websocket) failed to start. Looking in the browser console, the error was:
> kernel.js:461 Refused to connect to 'wss://notebooks.firecloud.org/notebooks/broad-firecloud-dsde/rt-long-running-test/api/kernels/8f09d2ef-d81c-4411-9314-fc3f37b39eab/channels?session_id=5dcf44675e01460c9dfa5807c14d577a' because it violates the following Content Security Policy directive: "connect-src 'self' wss://*.broadinstitute.org:* *.googleapis.com https://*.npmjs.org".
which pointed to the issue.
I manually made the config fix on prod and verified …

Added wss://notebooks.firecloud.org:* to CSP

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala

- Ensures that Sam is notified about cluster creation before returning a response, preventing 404s from GET cluster requests made immediate after PUT cluster responses.
- Adds more logging around cluster creation steps.

Bug fix for cluster creation API v2 

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala

I think this test failed because of this issue: https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/4154/
Basically `stagingBucket` was being returned as `null` in `getCluster` calls (which is possible when using the V2 createCluster API). The code was then wrapping the `null` in a `Some`, giving us: Some(GcsBucketName(null))`. This caused failures around [here](https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala#L125-L130) because the code just checks if the option is defined.
I changed the JSON deserialization code to use `Option(..)` instead of `Some(..)` which should correctly handle nulls.
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do …

Correctly handle null stagingBucket in the Cluster response

---

leonardo-example.conf

I've unsuccessfully to tried to come up with a test example to auto-verify the handling of large files and decided to leave it at updating the documentation only.

Example config update to set akka-http parsing max-content-length parameter

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/CorsSupport.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/ProxyRoutesSpec.scala

As discussed elsewhere in tech docs. This simply allows the X-App-Id in via ajax; I will be making separate PRs to actually send that header from the UI.
In all cases:

CORS support for X-App-Id header

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterConcurrencySpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/Leonardo.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20180919_stop_after_creation.xml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModelSpec.scala

In the API request `stopAfterCreation` flag is optional. Other than when it's specified as `Option(true)`, I mapped it to `false` (and not `Option(false)`) in the model and in the database for simplicity downstream, assuming that we don't need to distinguish between `stopAfterCreation` being `Option(false)` vs. `None`.

Persist stopAfterCreation flag (#579)

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala

Problem: if a "zombie" cluster starts getting monitored (for example at Leo startup) the `ClusterMonitorActor` goes into an infinite error loop. It logs errors like this:
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
"code" : 403,
"errors" : [ {
"domain" : "usageLimits",
"message" : "Cloud Dataproc API has not been used in project 713110123530 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=713110123530 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
"reason" : "accessNotConfigured",
"extendedHelp" : "https://console.developers.google.com"
} ],
"message" : "Cloud Dataproc API has …
```

Don't continually monitor zombie clusters

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterMonitoringSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPage.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebooksListPage.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala

See https://github.com/DataBiosphere/leonardo/issues/571
This increases selenium timeouts for opening notebooks, since it is observed that page loads are slow after resuming a cluster (but they should not fail).
Plan is to see if this improves the fail rate for the pause/resume tests, then evaluate if we need to do further work.
In all cases:

Increase selenium timeout for opening notebooks after resume

---

src/main/resources/jupyter/jupyter_notebook_config.py

Something changed and Leo started returning 502s for all requests to the notebooks proxy. This is causing all automation tests to fail since 9/28 8:40pm: https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/
The root cause is this error in jupyter.log:
```
Traceback (most recent call last):
File "/usr/local/bin/jupyter-notebook", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
app.initialize(argv)
File "<decorator-gen-7>", line 2, in initialize
File …
```

Change jupyter to listen on localhost instead of *

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoModelCopy.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala

Haven't run tests yet. This will hopefully help us debug cluster errors after start (and confirm a theory I have that a sqlite database is getting corrupted..).
In all cases:

Save jupyter.log to Jenkins after create and start cluster

---

jupyter-docker/Dockerfile

This is causing some build failures, so we should get this out sooner rather than later. I think this is included in @akarukappadath's dockerfire branch.
In all cases:

Upgrade java to u191, the old one doesn't exist anymore

---

src/test/resources/reference.conf
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/TestClusterSupervisorActor.scala

Hopefully addresses a common unit test flake:
```
java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.Terminated
at scala.Predef$.assert(Predef.scala:219)
at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:509)
at akka.testkit.TestKitBase.expectMsgClass(TestKit.scala:505)
at akka.testkit.TestKitBase.expectMsgClass$(TestKit.scala:505)
at akka.testkit.TestKit.expectMsgClass(TestKit.scala:896)
at org.broadinstitute.dsde.workbench.leonardo.monitor.ClusterMonitorSpec.$anonfun$new$3(ClusterMonitorSpec.scala:174)
at org.broadinstitute.dsde.workbench.leonardo.monitor.ClusterMonitorSpec.$anonfun$withClusterSupervisor$1(ClusterMonitorSpec.scala:113)
```
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do …

Increase akka patience in ClusterMonitorSpec

---

automation/project/Dependencies.scala

Ticket: GAWB-3947
update serviceTest version in automation, to pick up this bugfix from workbench-libs:
> bugfix: BillingFixtures.claimGPAllocProject now uses the proper OAuth scopes in the case where GPAlloc did not return a project and therefore the calling test needs to create one on the fly.
---
In all cases:

GAWB-3947: update serviceTest version to get bugfixes [risk: low]

---

src/main/resources/jupyter/google_sign_in.js

I noticed this in a lot of test console logs:
```
[2018-11-05T17:14:34+0000] [SEVERE] https://leonardo-fiab.dsde-qa.broadinstitute.org:30443/notebooks/gpalloc-qa-master-hgfhhlk/automation-test-al1imp9nz/custom/google_sign_in.js?v=20181105171319 86:22 Uncaught TypeError: Cannot read property 'postMessage' of null
```
It was probably introduced as a result of [this PR](https://github.com/DataBiosphere/leonardo/pull/644). There is no `window.opener` in tests so it was trying to use a null reference.
Complete speculation, but I was wondering if the uncaught error was causing other issues in the Jupyter JS code, perhaps leading to the "kernel not ready" test failures in https://broadinstitute.atlassian.net/browse/GAWB-3882.
Have you read …

Null check window.opener before using it

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCache.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dns/JupyterNameService.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/util/ValueBox.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCacheSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/util/ValueBoxTest.scala

@vkumra-broad Since we didn't get a chance to pair as we had hoped to, I'm making this PR into your branch to illustrate what I was going to suggest around making the mutable state in `ClusterDnsCache` safer. `ValueBox` code is from a previous project. Feel free to merge if helpful.

ValueBox - a mini library to encapsulate some of our thread-unsafe operations

---

src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml
src/main/resources/org/broadinstitute/dsde/workbench/leonardo/liquibase/changesets/20181126_cluster_image.xml
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/AllComponents.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterImageComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/DbReference.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisor.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/resources/jupyter/test-init-actions.sh
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterEnrichments.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/CommonTestData.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterImageComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModelSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

See https://github.com/DataBiosphere/leonardo/issues/692
Originally this was part of my RStudio branch but I decided to lift it into its own PR since it will be useful with the docker image upgrades as well. This change does the following:
- Adds a new optional `jupyterDockerImage` field to the `ClusterRequest` json
- If set, installs the specified Jupyter image on the cluster
- If unset, installs the latest "prod" image on the cluster (same behavior as today)
- Adds a new `CLUSTER_IMAGE` table which tracks the images installed on a cluster
In all cases:

[692] Allow users to pick their Jupyter image at cluster creation time

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterFixtureSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala

I'm hoping this will help address the intermittent failures in https://broadworkbench.atlassian.net/browse/WB-82. 
In all cases:

Automation tests: add jitter to project claim

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala

Fixes a race condition introduced by https://github.com/DataBiosphere/leonardo/pull/689.
1. Cluster is created via API. Record is inserted to the database with status Creating. Cluster is not created in Google yet.
2. ClusterMonitorSupervisor detects Creating cluster and starts monitoring it.
3. ClusterMonitorActor tries to delete cluster because it doesn't exist in Google yet.
4. Async cluster creation kicks in and finally creates cluster in Google.
5. End result is a cluster existing in Google with status `Deleted` in the Leo DB
6. Tests fail with messages like:
```
{"statusCode":404,"source":"leonardo","causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.leonardo.service.ClusterNotFoundException","stackTrace":[],"message":"Cluster …
```

Don't delete Creating clusters in the ClusterMonitorActor

---

automation/project/Dependencies.scala

Ticket: DataBiosphere/firecloud-app#109
adopts service-test changes from broadinstitute/workbench-libs#194
afaict Leo is oblivious to the functional change in serviceTest 0.15->0.16. Tests passed on a snapshot version of serviceTest 0.16; this PR updates the dependency to the official published  hash.
-----
In all cases:

update service-test to adopt billing scope change

---

src/main/resources/reference.conf
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/LeoExecutionModeConfig.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala
src/test/resources/reference.conf
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala

Adding configs to `reference.config` for now. These should be moved to `leonardo.conf` when we are ready to deploy multiple instances.
In all cases:

Issue 564 : Seperate front and back leo

---

docker/jupyter/run-jupyter-local.sh

This mostly fixed things.
Note: I still had problems with jupyter_notebook_config due to the change to `ip = "localhost"`. I was able to workaround this by reverting to '*' in combination with `allow_remote_access = True`. 127.0.0.1 also worked but I wasn't able to test that since I'm working remotely currently. Leaving that alone for now.
Context: I was using this to iterate on UI extension development. Probably could have used vanilla Jupyter just as easily but figured the Leo variant is slightly more realistic.

Update run-jupyter-local.sh post templating changes

---

leonardo-example.conf
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/DataprocConfig.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/package.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala
src/test/resources/reference.conf

Will open a firecloud-develop PR to configure the zone while there is an issue with `us-central1-f`. See https://google.secure.force.com/issuesupport?cid=500f200001LX8lsAAD&rs=717164544683127354&iid=a0rf200000MBvpfAAD&lang=en.
In all cases:

Make dataproc zone configurable

---

automation/project/Dependencies.scala

https://github.com/broadinstitute/workbench-libs/pull/196 fixed Chrome error `DevToolsActivePort file doesn't exist`.
In all cases:

update to latest version of workbench-lib serviceTest

---

project/Dependencies.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dns/ClusterDnsCache.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ZombieClusterMonitor.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/ClusterEnrichments.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala

I'm on-call and saw several Leo high CPU alerts on 2/12. I looked at some thread dumps and saw multiple threads here:
```
"leonardo-akka.actor.default-dispatcher-50705" #319469 prio=5 os_prio=0 tid=0x00007f4a5c04f800 nid=0x6b1d runnable [0x00007f49f6640000]
java.lang.Thread.State: RUNNABLE
at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:177)
at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:44)
at scala.collection.generic.Growable.loop$1(Growable.scala:53)
at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
at scala.collection.immutable.List.$colon$colon$colon(List.scala:128)
at …
```

More efficient database unmarshaling

---

docker/jupyter/Dockerfile

A test was failing (https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/10136/testReport/), and we suspect it might have to do with the discrepancy in versions between Spark and SparkR. This updates the SparkR version to 2.2.3 to match the Spark version to see if tests will pass. 
In all cases:

Change SparkR to 2.2.3

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookRKernelSpec.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala

1 test (`NotebookRKernelSpec`) is currently failing because Dataproc is installing Spark 2.2.1 but our version of sparkR depends on Spark 2.2.3.
Based on [this table](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.2), it looks like Spark 2.2.3 corresponds to Dataproc `1.2.65-deb9`. Hopefully specifying the Dataproc minor version will prevent future surprises.
In all cases:

Specify dataproc minor version to peg Spark at 2.2.3

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookRKernelSpec.scala

For some reason this test started failing:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/10438/testReport/org.broadinstitute.dsde.workbench.leonardo/NotebookRKernelSpec/Leonardo_notebooks_should_use_UTF_8_encoding/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/10438/artifact/failure_screenshots/NotebookRKernelSpec_14-11-15-596.png
I suspect it's grabbing the wrong cell output. Seeing if this fixes it.
In all cases:

Test fix: load library in a different cell

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/NotebookPyKernelSpec.scala
docker/jupyter/Dockerfile

See https://github.com/DataBiosphere/leonardo/issues/797. This bug report came from Yossi.
The ggplot fix essentially comes from here: https://stackoverflow.com/questions/50591982/importerror-cannot-import-name-timestamp
In all cases:

Fix ggplot on python 2

---

project/Dependencies.scala

Addresses some vulnerabilities in `jackson-databind` detected by SourceClear. For example: https://broadinstitute-dsp.sourceclear.io/workspaces/jppForw/issues/vulnerabilities/5952483/11678214
This is similar to this PR: https://github.com/broadinstitute/firecloud-orchestration/pull/707
In all cases:

Upgrade jackson to 2.9.8 to address CVE reports

---

docker/jupyter/Dockerfile

A new version of R (3.5.3) was released on the 11th and our dev builds were failing because of it. This pegs the R version to 3.5.2.
In all cases:

Dev build fix for R 

---

docker/jupyter/scripts/kernel/kernel_bootstrap.sh

See https://github.com/DataBiosphere/leonardo/issues/864
I validated this works manually on a Terra cluster. The suggested fix came from @mbookman.
In all cases:

[864] WORKSPACE_NAME environment variable is empty when workspace name has spaces

---

automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookClusterMonitoringSpec.scala
automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/notebooks/NotebookCustomizationSpec.scala
src/main/resources/swagger/api-docs.yaml
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/GoogleComputeDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleComputeDAO.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/google/GoogleModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/MockGoogleComputeDAO.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

See ticket: https://github.com/databiosphere/leonardo/issues/842
Before, our PATCH endpoint supported the following:
- add/removing worker nodes of the same type to a cluster
- changing autopause settings
Now, it does the following:
- add/removing worker nodes of the same type to a cluster
- changing autopause settings
- changing the master machine type (e.g. CPU and memory)
- increasing the master disk size
In all cases:

Expand scope of cluster PATCH endpoint

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponent.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/package.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/db/ClusterComponentSpec.scala

I stumbled upon this when explaining to Adelaide how to use the PATCH endpoint to disable auto-pause. To disable autopause, we set a "special" value of 0 in the database. However we weren't actually honoring this value in the DB query -- so instead we were autopausing the cluster _immediately_. This hopefully fixes it.
In all cases:

Bugfix: disabling auto-pause does not work

---

src/main/resources/reference.conf

Added:
- https://bvdp-saturn-staging.appspot.com 
- https://bvdp-saturn-perf.appspot.com 
- https://bvdp-saturn-alpha.appspot.com 
- https://firecloud.terra.bio
This needs to be included in the May 1 release since that is when https://firecloud.terra.bio is going live.
In all cases:

Added missing Terra domains to Content-Security-Policy

---

src/main/resources/reference.conf
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/Boot.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutes.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/LeoRoutesSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/api/TestLeoRoutes.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorSupervisorSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/AuthProviderSpec.scala
src/test/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoServiceSpec.scala

I noticed this and decided to remove it. This config was in place to support the old FC whitelist for notebooks -- it is not used by anyone anymore.
See also: https://github.com/broadinstitute/firecloud-develop/pull/1663/
In all cases:

Remove Leo whitelist config setting

---

docker/jupyter/Dockerfile
src/main/resources/jupyter/init-actions.sh
src/main/resources/jupyter/welder-docker-compose.yaml
src/main/resources/reference.conf
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala

It’s not clear why, but running Welder as an Entrypoint in its docker container does not allow it to find the [Application Default Credentials](https://cloud.google.com/docs/authentication/production) available on the host.
Welder does find the ADC if it is run inside the already-running container, so we defer execution in this way.  Interestingly, Jupyter already does this, for unrelated reasons.  Perhaps that is what enables Jupyter to use ADC as well.
In all cases:

[risk=no][IA-1026]Defer the execution of Welder until after its container is created

---

README.md

I tried to build Leo on my dev machine, which has Java 11 installed, and couldn't. As of Java 9, the `Nameservice` stuff [has been removed](https://bugs.openjdk.java.net/browse/JDK-8134577). This is causing [some consternation within the Java community](https://bugs.openjdk.java.net/browse/JDK-8192780) -- Google is unhappy, for one -- but at the very least, we should document the requirement.

Document that Leo requires Java 8

---

src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala
src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala

Rename addClusterLabels to augmentClusterRequest because it does more than labels
- split out the labeling to a new addClusterLabels
- refactor augmentClusterRequest
As I was poking around the cluster creation code regarding extensions, I was confused by this method which appeared to do two things.  So I couldn't resist doing a little refactoring.  Feel free to close this PR if it is not welcome. 
In all cases:

[no JIRA][risk=no] Rename and refactor addClusterLabels
